import type { MetadataRoute } from 'next';
import { BRAND } from '@/lib/constants';

/**
 * /robots.txt — generated by Next.js. Allows all crawlers across the whole
 * site and points them at the sitemap so new pages are discovered quickly.
 * Next's image/metadata helper routes (e.g. the generated OG image) are not
 * disallowed, so social-card unfurls keep working.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
    },
    sitemap: `${BRAND.url}/sitemap.xml`,
    host: BRAND.url,
  };
}
